From golang:1.17 as buils_sales-api
ENV CGO_ENABLED=0
ARG BUILD_REF

# Copy Source Code 
COPY . /service 

WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine.
FROM alpine:3.16
ARG BUILD_DATE
ARG BUILD_REF
RUN addgroup -g 1000 -S sales && \
    adduser -u 1000 -h /service -G sales -S sales
COPY --from=buils_sales-api /service/services /service/services
WORKDIR /service
CMD ["./services"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="chetan kolhe <chetankolhe72@ardanlabs.com>" \
      org.opencontainers.image.source="https://github.com/chetankolhe/service" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Automation"